### ISSUE TITLE
[Help]: is FFmpeg5 a requirement for MFDF?

### ISSUE THREAD

**Issue by RevENGE-code** [David-Maisonave/MediaFileDuplicateFinder#2]
### Please enter a clear and concise detailed question.

Since `06fe8a6`, `VDF` supports native ffmpeg v6 bindings. Please add it to MFDF as well. Also, please update the readme to reflect this, currently the readme doesn't outline any required FFmpeg version. Which for me returns `Cannot find shared FFmpeg libraries`.

### What Operating System (OS)?

MacOS 13.4 (22F66)

### What version of MediaFileDuplicateFinder?

1.2

### Where did you download MediaFileDuplicateFinder from?

GitHub

**Comment by David-Maisonave** [comment]
Sorry for late reply.  My email was down.

>> Since 06fe8a6, VDF supports native ffmpeg v6 bindings. Please add it to MFDF as well. 

Do you have any sample MFDF files which I can use for testing?
I would be happy to add support for MFDF if I have some sample files to work with. I did a google search, but didn't get any results with MFDF files to download.

>> Also, please update the readme to reflect this, currently the readme doesn't outline any required FFmpeg version. Which for me returns Cannot find shared FFmpeg libraries.

I'll update the readme.
I was able to duplicate this issue on Windows.  As a temporary workaround, you can disable option [**Use native Ffmpeg binding**]
<img width="302" alt="DisableUseNativeFfmpegBinding" src="https://github.com/David-Maisonave/MediaFileDuplicateFinder/assets/47364845/54dac823-a188-4be7-8037-257f56fcdcb4">

I'll update you as soon as I have a fix.

Thank you for reporting this issue.

**Comment by David-Maisonave** [comment]
The native Ffmpeg option only seems to work with share GPL. See following link for downloads: [https://github.com/BtbN/FFmpeg-Builds/releases/latest](https://github.com/BtbN/FFmpeg-Builds/releases/latest)

However, I ran some test with this option enabled and disabled, and there was only a small difference in performance. Moreover the native option missed some duplicates which were caught by the Non-Native run. I ran this test with VDF to make sure the new code in MFDF was causing any issues. See following results:
- 5.0 FfMpeg binaries
  -<img width="470" alt="NativeFfmpegPerformance_5 0" src="https://github.com/David-Maisonave/MediaFileDuplicateFinder/assets/47364845/3d06c1ee-0b81-454a-8676-06f4afc59f7e">
- 6.0 FfMpeg binaries
  -<img width="469" alt="NativeFfmpegPerformance_6 0" src="https://github.com/David-Maisonave/MediaFileDuplicateFinder/assets/47364845/09f946f1-141e-425d-ba8c-92ebfe98db51">

The main reason for this option is because native mode is supposed to be much faster, but at least in Windows, this does not seem to be the case.

I couldn't find the FFMpeg share GPL MacOS version for download, and unfortunately I don't have a Mac machine which I can use to test this out on.
If you can find the FFMpeg share GPL MacOS binaries, can you please download and test this out on your Mac machine.

>> Since 06fe8a6, VDF supports native ffmpeg v6 bindings.
If the test in other platforms show similar results to the test on Windows, I'm not sure if it's a good idea to continue binding support.  There's only about a 10% difference, and that could be cause by the more accurate results being produced by the non-native mode.
I need to find out why the native mode is failing to catch some of the duplicates before working on v6 binding.

**Comment by David-Maisonave** [comment]
Added Ffmpeg 6.0 support.
For Windows MSI package, the 6.0 share GPL is now included.
